export const
    ADD_INGREDIENTS = 'ADD_INGREDIENTS',
    REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS',
    SET_INGREDIENTS = 'SET_INGREDIENTS',
    FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'
;

export const
    PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS',
    PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED',
    PURCHASE_BURGER_START = 'PURCHASE_BURGER_START',
    PURCHASE_INIT = 'PURCHASE_INIT'
;

export const
    FETCH_ORDERS_START = 'FETCH_ORDERS_START',
    FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS',
    FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED'
;