export const
    ADD_INGREDIENTS = 'ADD_INGREDIENTS',
    REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS',
    SET_INGREDIENTS = 'SET_INGREDIENTS',
    FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'
;

export const
    PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS',
    PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED',
    PURCHASE_BURGER_START = 'PURCHASE_BURGER_START',
    PURCHASE_INIT = 'PURCHASE_INIT'
;

export const
    FETCH_ORDERS_START = 'FETCH_ORDERS_START',
    FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS',
    FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED'
;

export const
    AUTH_START = 'AUTH_START',
    AUTH_SUCCESS = 'AUTH_SUCCESS',
    AUTH_FAIL = 'AUTH_FAIL',
    AUTH_LOGOUT = 'AUTH_LOGOUT'
;

export const
    SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH"
;
